name: Assign PR Reviewer

on:
  workflow_dispatch:
    inputs:
      reviewer:
        description: 'GitHub username of the reviewer to assign'
        required: true
        type: string
      pr_number:
        description: 'Pull request number'
        required: true
        type: string

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Assign Reviewer to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Assign the reviewer to the PR
          gh pr edit ${{ github.event.inputs.pr_number }} --add-reviewer "${{ github.event.inputs.reviewer }}"
          
          # Post a confirmation comment
          gh pr comment ${{ github.event.inputs.pr_number }} --body "🤖 **Reviewer Assigned**: @${{ github.event.inputs.reviewer }} has been requested to review this PR."
          
      - name: Handle Assignment Failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.inputs.pr_number }} --body "⚠️ **Assignment Failed**: Could not assign @${{ github.event.inputs.reviewer }} as a reviewer. Please check if the username is valid and they have repository access."
